inherit_from: .rubocop_todo.yml

Style/FileName:
  Exclude:
    - 'lib/vagrant-vsphere.rb'

Lint/RescueException:
  Exclude:
    # the logic in the method `find_clustercompute_or_compute_resource` does not
    # work when rescuing StandardError, so exclude
    # lib/vSphere/util/vim_helpers.rb to continue rescuing Exception in that
    # method
    - 'lib/vSphere/util/vim_helpers.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Disabled these cops upgrading rubocop to 1.25.0
# TODO:Correct the issues found by these cops someday
Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming:
  Enabled: false

# TODO: Add required ruby version to gemspec
Gemspec/RequiredRubyVersion:
  Enabled: false
